---
title: "Data Acquisition Mastersheet"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(httr)
```

## **SCRAPING STATS FROM 18-19 SEASON**

```{r}
goalkeeping18.19 <- read_html("https://fbref.com/en/comps/8/2018-2019/keepers/2018-2019-Champions-League-Stats")

table <- html_nodes(goalkeeping18.19, css = "table")

goalkeeping18.19 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:21) {
  new_column_name <- goalkeeping18.19[1,i]
  colnames(goalkeeping18.19)[i] <- new_column_name
}

goalkeeping18.19 <- goalkeeping18.19[-1,-21]
```

```{r}
advancedgoalkeeping18.19 <- read_html("https://fbref.com/en/comps/8/2018-2019/keepersadv/2018-2019-Champions-League-Stats")

table <- html_nodes(advancedgoalkeeping18.19, css = "table")

advancedgoalkeeping18.19 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:28) {
  new_column_name <- advancedgoalkeeping18.19[1,i]
  colnames(advancedgoalkeeping18.19)[i] <- new_column_name
}

advancedgoalkeeping18.19 <- advancedgoalkeeping18.19[-1,c(-20:-22)]
```

```{r}
defensive18.19 <- read_html("https://fbref.com/en/comps/8/2018-2019/defense/2018-2019-Champions-League-Stats")

table <- html_nodes(defensive18.19, css = "table")

defensive18.19 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:19) {
  new_column_name <- defensive18.19[1,i]
  colnames(defensive18.19)[i] <- new_column_name
}

defensive18.19 <- defensive18.19[-1,-9]
```

```{r}
passing18.19 <- read_html("https://fbref.com/en/comps/8/2018-2019/passing/2018-2019-Champions-League-Stats")

table <- html_nodes(passing18.19, css = "table")

passing18.19 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:26) {
  new_column_name <- passing18.19[1,i]
  colnames(passing18.19)[i] <- new_column_name
}

passing18.19 <- passing18.19[-1, c(-9:-17)]
```

```{r}
possession18.19 <- read_html("https://fbref.com/en/comps/8/2018-2019/possession/2018-2019-Champions-League-Stats")

table <- html_nodes(possession18.19, css = "table")

possession18.19 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:26) {
  new_column_name <- possession18.19[1,i]
  colnames(possession18.19)[i] <- new_column_name
}

possession18.19 <- possession18.19[-1,]
```

```{r}
shooting18.19 <- read_html("https://fbref.com/en/comps/8/2018-2019/shooting/2018-2019-Champions-League-Stats")

table <- html_nodes(shooting18.19, css = "table")

shooting18.19 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:20) {
  new_column_name <- shooting18.19[1,i]
  colnames(shooting18.19)[i] <- new_column_name
}

shooting18.19 <- shooting18.19[-1,]
```

```{r}
shotcreation18.19 <- read_html("https://fbref.com/en/comps/8/2018-2019/gca/2018-2019-Champions-League-Stats")

table <- html_nodes(shotcreation18.19, css = "table")

shotcreation18.19 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:19) {
  new_column_name <- shotcreation18.19[1,i]
  colnames(shotcreation18.19)[i] <- new_column_name
}

shotcreation18.19 <- shotcreation18.19[-1,c(-14:-19)]
```

## **SCRAPING STATS FROM 19-20 SEASON**

```{r}
goalkeeping19.20 <- read_html("https://fbref.com/en/comps/8/2019-2020/keepers/2019-2020-Champions-League-Stats")

table <- html_nodes(goalkeeping19.20, css = "table")

goalkeeping19.20 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:21) {
  new_column_name <- goalkeeping19.20[1,i]
  colnames(goalkeeping19.20)[i] <- new_column_name
}

goalkeeping19.20 <- goalkeeping19.20[-1,-21]
```

```{r}
advancedgoalkeeping19.20 <- read_html("https://fbref.com/en/comps/8/2019-2020/keepersadv/2019-2020-Champions-League-Stats")

table <- html_nodes(advancedgoalkeeping19.20, css = "table")

advancedgoalkeeping19.20 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:28) {
  new_column_name <- advancedgoalkeeping19.20[1,i]
  colnames(advancedgoalkeeping19.20)[i] <- new_column_name
}

advancedgoalkeeping19.20 <- advancedgoalkeeping19.20[-1,c(-20:-22)]
```

```{r}
defensive19.20 <- read_html("https://fbref.com/en/comps/8/2019-2020/defense/2019-2020-Champions-League-Stats")

table <- html_nodes(defensive19.20, css = "table")

defensive19.20 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:19) {
  new_column_name <- defensive19.20[1,i]
  colnames(defensive19.20)[i] <- new_column_name
}

defensive19.20 <- defensive19.20[-1,-9]
```

```{r}
passing19.20 <- read_html("https://fbref.com/en/comps/8/2019-2020/passing/2019-2020-Champions-League-Stats")

table <- html_nodes(passing19.20, css = "table")

passing19.20 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:26) {
  new_column_name <- passing19.20[1,i]
  colnames(passing19.20)[i] <- new_column_name
}

passing19.20 <- passing19.20[-1,c(-9:-17)]
```

```{r}
possession19.20 <- read_html("https://fbref.com/en/comps/8/2019-2020/possession/2019-2020-Champions-League-Stats")

table <- html_nodes(possession19.20, css = "table")

possession19.20 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:26) {
  new_column_name <- possession19.20[1,i]
  colnames(possession19.20)[i] <- new_column_name
}

possession19.20 <- possession19.20[-1,]
```

```{r}
shotcreation19.20 <- read_html("https://fbref.com/en/comps/8/2019-2020/gca/2019-2020-Champions-League-Stats")

table <- html_nodes(shotcreation19.20, css = "table")

shotcreation19.20 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:19) {
  new_column_name <- shotcreation19.20[1,i]
  colnames(shotcreation19.20)[i] <- new_column_name
}

shotcreation19.20 <- shotcreation19.20[-1,c(-14:-19)]
```

```{r}
shooting19.20 <- read_html("https://fbref.com/en/comps/8/2019-2020/shooting/2019-2020-Champions-League-Stats")

table <- html_nodes(shooting19.20, css = "table")

shooting19.20 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:20) {
  new_column_name <- shooting19.20[1,i]
  colnames(shooting19.20)[i] <- new_column_name
}

shooting19.20 <- shooting19.20[-1,]
```

## **SCRAPING STATS FROM 20-21 SEASON**

```{r}
goalkeeping20.21 <- read_html("https://fbref.com/en/comps/8/2020-2021/keepers/2020-2021-Champions-League-Stats")

table <- html_nodes(goalkeeping20.21, css = "table")

goalkeeping20.21 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:21) {
  new_column_name <- goalkeeping20.21[1,i]
  colnames(goalkeeping20.21)[i] <- new_column_name
}

goalkeeping20.21 <- goalkeeping20.21[-1,-21]
```

```{r}
advancedgoalkeeping20.21 <- read_html("https://fbref.com/en/comps/8/2020-2021/keepersadv/2020-2021-Champions-League-Stats")

table <- html_nodes(advancedgoalkeeping20.21, css = "table")

advancedgoalkeeping20.21 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:28) {
  new_column_name <- advancedgoalkeeping20.21[1,i]
  colnames(advancedgoalkeeping20.21)[i] <- new_column_name
}

advancedgoalkeeping20.21 <- advancedgoalkeeping20.21[-1,c(-20:-22)]
```

```{r}
defensive20.21 <- read_html("https://fbref.com/en/comps/8/2020-2021/defense/2020-2021-Champions-League-Stats")

table <- html_nodes(defensive20.21, css = "table")

defensive20.21 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:19) {
  new_column_name <- defensive20.21[1,i]
  colnames(defensive20.21)[i] <- new_column_name
}

defensive20.21 <- defensive20.21[-1,-9]
```

```{r}
passing20.21 <- read_html("https://fbref.com/en/comps/8/2020-2021/passing/2020-2021-Champions-League-Stats")

table <- html_nodes(passing20.21, css = "table")

passing20.21 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:26) {
  new_column_name <- passing20.21[1,i]
  colnames(passing20.21)[i] <- new_column_name
}

passing20.21 <- passing20.21[-1,c(-9:-17)]
```

```{r}
possession20.21 <- read_html("https://fbref.com/en/comps/8/2020-2021/possession/2020-2021-Champions-League-Stats")

table <- html_nodes(possession20.21, css = "table")

possession20.21 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:26) {
  new_column_name <- possession20.21[1,i]
  colnames(possession20.21)[i] <- new_column_name
}

possession20.21 <- possession20.21[-1,]
```

```{r}
shotcreation20.21 <- read_html("https://fbref.com/en/comps/8/2020-2021/gca/2020-2021-Champions-League-Stats")

table <- html_nodes(shotcreation20.21, css = "table")

shotcreation20.21 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:19) {
  new_column_name <- shotcreation20.21[1,i]
  colnames(shotcreation20.21)[i] <- new_column_name
}

shotcreation20.21 <- shotcreation20.21[-1,c(-14:-19)]
```

```{r}
shooting20.21 <- read_html("https://fbref.com/en/comps/8/2020-2021/shooting/2020-2021-Champions-League-Stats")

table <- html_nodes(shooting20.21, css = "table")

shooting20.21 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:20) {
  new_column_name <- shooting20.21[1,i]
  colnames(shooting20.21)[i] <- new_column_name
}

shooting20.21 <- shooting20.21[-1,]
```

## **SCRAPING STATS FROM 21-22 SEASON**

```{r}
goalkeeping21.22 <- read_html("https://fbref.com/en/comps/8/2021-2022/keepers/2021-2022-Champions-League-Stats")

table <- html_nodes(goalkeeping21.22, css = "table")

goalkeeping21.22 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:21) {
  new_column_name <- goalkeeping21.22[1,i]
  colnames(goalkeeping21.22)[i] <- new_column_name
}

goalkeeping21.22 <- goalkeeping21.22[-1,-21]
```

```{r}
advancedgoalkeeping21.22 <- read_html("https://fbref.com/en/comps/8/2021-2022/keepersadv/2021-2022-Champions-League-Stats")

table <- html_nodes(advancedgoalkeeping21.22, css = "table")

advancedgoalkeeping21.22 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:28) {
  new_column_name <- advancedgoalkeeping21.22[1,i]
  colnames(advancedgoalkeeping21.22)[i] <- new_column_name
}

advancedgoalkeeping21.22 <- advancedgoalkeeping21.22[-1,c(-20:-22)]
```

```{r}
defensive21.22 <- read_html("https://fbref.com/en/comps/8/2021-2022/defense/2021-2022-Champions-League-Stats")

table <- html_nodes(defensive21.22, css = "table")

defensive21.22 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:19) {
  new_column_name <- defensive21.22[1,i]
  colnames(defensive21.22)[i] <- new_column_name
}

defensive21.22 <- defensive21.22[-1,-9]
```

```{r}
passing21.22 <- read_html("https://fbref.com/en/comps/8/2021-2022/passing/2021-2022-Champions-League-Stats")

table <- html_nodes(passing21.22, css = "table")

passing21.22 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:26) {
  new_column_name <- passing21.22[1,i]
  colnames(passing21.22)[i] <- new_column_name
}

passing21.22 <- passing21.22[-1,c(-9:-17)]
```

```{r}
possession21.22 <- read_html("https://fbref.com/en/comps/8/2021-2022/possession/2021-2022-Champions-League-Stats")

table <- html_nodes(possession21.22, css = "table")

possession21.22 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:26) {
  new_column_name <- possession21.22[1,i]
  colnames(possession21.22)[i] <- new_column_name
}

possession21.22 <- possession21.22[-1,]
```

```{r}
shotcreation21.22 <- read_html("https://fbref.com/en/comps/8/2021-2022/gca/2021-2022-Champions-League-Stats")

table <- html_nodes(shotcreation21.22, css = "table")

shotcreation21.22 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:19) {
  new_column_name <- shotcreation21.22[1,i]
  colnames(shotcreation21.22)[i] <- new_column_name
}

shotcreation21.22 <- shotcreation21.22[-1,c(-14:-19)]
```

```{r}
shooting21.22 <- read_html("https://fbref.com/en/comps/8/2021-2022/shooting/2021-2022-Champions-League-Stats")

table <- html_nodes(shooting21.22, css = "table")

shooting21.22 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:20) {
  new_column_name <- shooting21.22[1,i]
  colnames(shooting21.22)[i] <- new_column_name
}

shooting21.22 <- shooting21.22[-1,]
```

## **SCRAPING STATS FROM 22-23 SEASON**

```{r}
goalkeeping22.23 <- read_html("https://fbref.com/en/comps/8/2022-2023/keepers/2020-2021-Champions-League-Stats")

table <- html_nodes(goalkeeping22.23, css = "table")

goalkeeping22.23 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:21) {
  new_column_name <- goalkeeping22.23[1,i]
  colnames(goalkeeping22.23)[i] <- new_column_name
}

goalkeeping22.23 <- goalkeeping22.23[-1,-21]
```

```{r}
advancedgoalkeeping22.23 <- read_html("https://fbref.com/en/comps/8/2022-2023/keepersadv/2022-2023-Champions-League-Stats")

table <- html_nodes(advancedgoalkeeping22.23, css = "table")

advancedgoalkeeping22.23 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:28) {
  new_column_name <- advancedgoalkeeping22.23[1,i]
  colnames(advancedgoalkeeping22.23)[i] <- new_column_name
}

advancedgoalkeeping22.23 <- advancedgoalkeeping22.23[-1,c(-20:-22)]
```

```{r}
defensive22.23 <- read_html("https://fbref.com/en/comps/8/2022-2023/defense/2022-2023-Champions-League-Stats")

table <- html_nodes(defensive22.23, css = "table")

defensive22.23 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:19) {
  new_column_name <- defensive22.23[1,i]
  colnames(defensive22.23)[i] <- new_column_name
}

defensive22.23 <- defensive22.23[-1,-9]
```

```{r}
passing22.23 <- read_html("https://fbref.com/en/comps/8/2022-2023/passing/2022-2023-Champions-League-Stats")

table <- html_nodes(passing22.23, css = "table")

passing22.23 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:26) {
  new_column_name <- passing22.23[1,i]
  colnames(passing22.23)[i] <- new_column_name
}

passing22.23 <- passing22.23[-1,c(-9:-17)]
```

```{r}
possession22.23 <- read_html("https://fbref.com/en/comps/8/2022-2023/possession/2022-2023-Champions-League-Stats")

table <- html_nodes(possession22.23, css = "table")

possession22.23 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:26) {
  new_column_name <- possession22.23[1,i]
  colnames(possession22.23)[i] <- new_column_name
}

possession22.23 <- possession22.23[-1,]
```

```{r}
shotcreation22.23 <- read_html("https://fbref.com/en/comps/8/2022-2023/gca/2022-2023-Champions-League-Stats")

table <- html_nodes(shotcreation22.23, css = "table")

shotcreation22.23 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:19) {
  new_column_name <- shotcreation22.23[1,i]
  colnames(shotcreation22.23)[i] <- new_column_name
}

shotcreation22.23 <- shotcreation22.23[-1,c(-14:-19)]
```

```{r}
shooting22.23 <- read_html("https://fbref.com/en/comps/8/2022-2023/shooting/2022-2023-Champions-League-Stats")

table <- html_nodes(shooting22.23, css = "table")

shooting22.23 <- html_table(table, header = TRUE, fill = TRUE)[[1]]

for(i in 1:20) {
  new_column_name <- shooting22.23[1,i]
  colnames(shooting22.23)[i] <- new_column_name
}

shooting22.23 <- shooting22.23[-1,]
```

## **SCRAPING PERFORMANCE DATA FOR EACH SEASON**

```{r}
placement22.23 <- read_html("https://fbref.com/en/comps/8/2022-2023/2022-2023-Champions-League-Stats") |>
  html_nodes("#results2022-202380_overall th.right") |>
  html_text()
```

```{r}
squad22.23 <- read_html("https://fbref.com/en/comps/8/2022-2023/2022-2023-Champions-League-Stats") |>
  html_nodes("#results2022-202380_overall .left:nth-child(2)") |>
  html_text()
```

```{r}
performance22.23 <- tibble(squad22.23, placement22.23) |>
  filter(str_detect(squad22.23, "[1-9A-Z]")) |>
  rename(Squad = squad22.23,
         Rank = placement22.23) 
performance22.23[1,2] = "W"
performance22.23[2,2] = "F"
```

```{r}
placement21.22 <- read_html("https://fbref.com/en/comps/8/2021-2022/2021-2022-Champions-League-Stats") |>
  html_nodes("#results2021-202280_overall th.right") |>
  html_text()
```

```{r}
squad21.22 <- read_html("https://fbref.com/en/comps/8/2021-2022/2021-2022-Champions-League-Stats") |>
  html_nodes("#results2021-202280_overall .left:nth-child(2)") |>
  html_text()
```

```{r}
performance21.22 <- tibble(squad21.22, placement21.22) |>
  filter(str_detect(squad21.22, "[1-9A-Z]")) |>
  rename(Squad = squad21.22,
         Rank = placement21.22)
performance21.22[1,2] = "W"
performance21.22[2,2] = "F"
```

```{r}
placement20.21 <- read_html("https://fbref.com/en/comps/8/2020-2021/2020-2021-Champions-League-Stats") |>
  html_nodes("#results2020-202180_overall th.right") |>
  html_text()
```

```{r}
squad20.21 <- read_html("https://fbref.com/en/comps/8/2020-2021/2020-2021-Champions-League-Stats") |>
  html_nodes("#results2020-202180_overall .left:nth-child(2)") |>
  html_text()
```

```{r}
performance20.21 <- tibble(squad20.21, placement20.21) |>
  filter(str_detect(squad20.21, "[1-9A-Z]")) |>
  rename(Squad = squad20.21,
         Rank = placement20.21)
```

```{r}
placement19.20 <- read_html("https://fbref.com/en/comps/8/2019-2020/2019-2020-Champions-League-Stats") |>
  html_nodes("#results2019-202080_overall th.right") |>
  html_text()
```

```{r}
squad19.20 <- read_html("https://fbref.com/en/comps/8/2019-2020/2019-2020-Champions-League-Stats") |>
  html_nodes("#results2019-202080_overall .left:nth-child(2)") |>
  html_text()
```

```{r}
performance19.20 <- tibble(squad19.20, placement19.20) |>
  filter(str_detect(squad19.20, "[1-9A-Z]")) |>
  rename(Squad = squad19.20,
         Rank = placement19.20)
```

```{r}
placement18.19 <- read_html("https://fbref.com/en/comps/8/2018-2019/2018-2019-Champions-League-Stats") |>
  html_nodes("#results2018-201980_overall th.right") |>
  html_text()
```

```{r}
squad18.19 <- read_html("https://fbref.com/en/comps/8/2018-2019/2018-2019-Champions-League-Stats") |>
  html_nodes("#results2018-201980_overall .left:nth-child(2)") |>
  html_text()
```

```{r}
performance18.19 <- tibble(squad18.19, placement18.19) |>
  filter(str_detect(squad18.19, "[1-9A-Z]")) |>
  rename(Squad = squad18.19, 
         Rank = placement18.19)
```

## **JOINS 18-19**

```{r}
totalgoalkeeping18.19 <- goalkeeping18.19 |>
  right_join(advancedgoalkeeping18.19, join_by(Squad == Squad))
ds18.19 <- totalgoalkeeping18.19 |>
  right_join(defensive18.19, join_by(Squad == Squad)) |>
  mutate(across(-1, parse_number),
         Year = "18/19")
ds18.19 <- performance18.19 |>
  right_join(ds18.19, join_by(Squad == Squad)) |>
  mutate(Squad = str_extract(Squad, "[A-Z].*"))
```

```{r}
ps18.19 <- possession18.19 |>
  right_join(passing18.19, join_by(Squad == Squad)) |>
  mutate(across(-1, parse_number),
         Year = "18/19")
ps18.19 <- performance18.19 |>
  right_join(ps18.19, join_by(Squad == Squad)) |>
  mutate(Squad = str_extract(Squad, "[A-Z].*"))
```

```{r}
gs18.19 <- shotcreation18.19 |>
  right_join(shooting18.19, join_by(Squad == Squad)) |>
  mutate(across(-1, parse_number),
         Year = "18/19")
gs18.19 <- performance18.19 |>
  right_join(gs18.19, join_by(Squad == Squad)) |>
  mutate(Squad = str_extract(Squad, "[A-Z].*"))
```

## **JOINS 19-20**

```{r}
totalgoalkeeping19.20 <- goalkeeping19.20 |>
  right_join(advancedgoalkeeping19.20, join_by(Squad == Squad))
ds19.20 <- totalgoalkeeping19.20 |>
  right_join(defensive19.20, join_by(Squad == Squad)) |>
  mutate(across(-1, parse_number),
         Year = "19/20")
ds19.20 <- performance19.20 |>
  right_join(ds19.20, join_by(Squad == Squad)) |>
  mutate(Squad = str_extract(Squad, "[A-Z].*"))
```

```{r}
ps19.20 <- possession19.20 |>
  right_join(passing19.20, join_by(Squad == Squad)) |>
  mutate(across(-1, parse_number),
         Year = "19/20")
ps19.20 <- performance19.20 |>
  right_join(ps19.20, join_by(Squad == Squad)) |>
  mutate(Squad = str_extract(Squad, "[A-Z].*"))
```

```{r}
gs19.20 <- shotcreation19.20 |>
  right_join(shooting19.20, join_by(Squad == Squad)) |>
  mutate(across(-1, parse_number),
         Year = "19/20")
gs19.20 <- performance19.20 |>
  right_join(gs19.20, join_by(Squad == Squad)) |>
  mutate(Squad = str_extract(Squad, "[A-Z].*"))
```

## **JOINS 20-21**

```{r}
totalgoalkeeping20.21 <- goalkeeping20.21 |>
  right_join(advancedgoalkeeping20.21, join_by(Squad == Squad))
ds20.21 <- totalgoalkeeping20.21 |>
  right_join(defensive20.21, join_by(Squad == Squad)) |>
  mutate(across(-1, parse_number),
         Year = "20/21")
ds20.21 <- performance20.21 |>
  right_join(ds20.21, join_by(Squad == Squad)) |>
  mutate(Squad = str_extract(Squad, "[A-Z].*"))
```

```{r}
ps20.21 <- possession20.21 |>
  right_join(passing20.21, join_by(Squad == Squad)) |>
  mutate(across(-1, parse_number),
         Year = "20/21")
ps20.21 <- performance20.21 |>
  right_join(ps20.21, join_by(Squad == Squad)) |>
  mutate(Squad = str_extract(Squad, "[A-Z].*"))
```

```{r}
gs20.21 <- shotcreation20.21 |>
  right_join(shooting20.21, join_by(Squad == Squad)) |>
  mutate(across(-1, parse_number),
         Year = "20/21")
gs20.21 <- performance20.21 |>
  right_join(gs20.21, join_by(Squad == Squad)) |>
  mutate(Squad = str_extract(Squad, "[A-Z].*"))
```

## **JOINS 21-22**

```{r}
totalgoalkeeping21.22 <- goalkeeping21.22 |>
  right_join(advancedgoalkeeping21.22, join_by(Squad == Squad))
ds21.22 <- totalgoalkeeping21.22 |>
  right_join(defensive21.22, join_by(Squad == Squad)) |>
  mutate(across(-1, parse_number),
         Year = "21/22")
ds21.22 <- performance21.22 |>
  right_join(ds21.22, join_by(Squad == Squad)) |>
  mutate(Squad = str_extract(Squad, "[A-Z].*"))
```

```{r}
ps21.22 <- possession21.22 |>
  right_join(passing21.22, join_by(Squad == Squad)) |>
  mutate(across(-1, parse_number),
         Year = "21/22")
ps21.22 <- performance21.22 |>
  right_join(ps21.22, join_by(Squad == Squad)) |>
  mutate(Squad = str_extract(Squad, "[A-Z].*"))
```

```{r}
gs21.22 <- shotcreation21.22 |>
  right_join(shooting21.22, join_by(Squad == Squad)) |>
  mutate(across(-1, parse_number),
         Year = "21/22")
gs21.22 <- performance21.22 |>
  right_join(gs21.22, join_by(Squad == Squad)) |>
  mutate(Squad = str_extract(Squad, "[A-Z].*"))
```

## **JOINS 22-23**

```{r}
totalgoalkeeping22.23 <- goalkeeping22.23 |>
  right_join(advancedgoalkeeping22.23, join_by(Squad == Squad))
ds22.23 <- totalgoalkeeping22.23 |>
  right_join(defensive22.23, join_by(Squad == Squad)) |>
  mutate(across(-1, parse_number),
         Year = "22/23")
ds22.23 <- performance22.23 |>
  right_join(ds22.23, join_by(Squad == Squad)) |>
  mutate(Squad = str_extract(Squad, "[A-Z].*"))
```

```{r}
ps22.23 <- possession22.23 |>
  right_join(passing22.23, join_by(Squad == Squad)) |>
  mutate(across(-1, parse_number),
         Year = "22/23")
ps22.23 <- performance22.23 |>
  right_join(ps22.23, join_by(Squad == Squad)) |>
  mutate(Squad = str_extract(Squad, "[A-Z].*"))
```

```{r}
gs22.23 <- shotcreation22.23 |>
  right_join(shooting22.23, join_by(Squad == Squad)) |>
  mutate(across(-1, parse_number),
         Year = "22/23")
gs22.23 <- performance22.23 |>
  right_join(gs22.23, join_by(Squad == Squad)) |>
  mutate(Squad = str_extract(Squad, "[A-Z].*"))
gs22.23[1,2] = "W"
gs22.23[2,2] = "F"
  
```

## **BINDING ROWS AND ADDING USER CREATED VARIABLES**

```{r}
gs <- rbind(gs22.23, gs21.22, gs20.21, gs19.20, gs18.19) |>
  select(1, 34, 2:33) |>
  mutate(prop_SCA_dead = PassDead/SCA,
         performance = ifelse(`G-xG` > 0, "Overperformed", "Underperformed"))

ps <- rbind(ps22.23, ps21.22, ps20.21, ps19.20, ps18.19) |>
  select(1, 44, 2:43) |>
  mutate(takeons_per_match = Att.x/`90s.x`,
         prop_def_third = `Def 3rd`/Touches,
         prop_mid_third = `Mid 3rd`/Touches,
         prop_att_third = `Att 3rd`/Touches,
         kp_90 = KP/`90s.x`,
crosses_90 = CrsPA/`90s.x`,
PrgP_90 = PrgP/`90s.x`,
PrgC_90 = PrgC/`90s.x`,
takeons_attempted_90 = Att.x/`90s.x`,
def_third_touches_90 = `Def 3rd`/`90s.x`,
mid_third_touches_90 = `Mid 3rd`/`90s.x`,
att_third_touches_90 = `Att 3rd`/`90s.x`)
ds <- rbind(ds22.23, ds21.22, ds20.21, ds19.20, ds18.19) |>
  select(1, 63, 2:62) |>
   mutate(opp_90 = Opp/`90s.x`,
         tkl_90 = Tkl/`90s.x`,
         int_90 = Int/`90s.x`, 
         tkl_int_90 = `Tkl+Int`/`90s.x`,
         def_3rd_90 = `Def 3rd`/`90s.x`,
         att_3rd_90 = `Att 3rd`/`90s.x`,
         save_performance = ifelse(`PSxG+/-` > 0, "Overperformed", "Underperformed"),
         prop_tkl_w = TklW/Tkl)
```

```{r}
total_s <- merge(gs, ps, by = c("Squad", "Year"), all = FALSE)

total_s <- merge(total_s, ds, by = c("Squad", "Year"), all = FALSE)
```


## **WRITING THE CSV FILES!!!**

```{r}
write_csv(gs, "gs.csv")
write_csv(ps, "ps.csv")
write_csv(ds, "ds.csv")
write_csv(total_s, "total_s.csv")
```
