---
title: "Champions League Progression"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    theme: 
      version: 5
      bootswatch: lux
---


```{r, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(rvest)
library(httr)
library(ggplot2)
library(readr)
library(plotly)
library(flexdashboard)
library(ggthemes)
library(shinyWidgets)
library(reshape2)
library(gt)
```

```{r, echo = FALSE}
gs <- read_csv("gs.csv")
ps <- read_csv("ps.csv")
ds <- read_csv("ds.csv")
total_s <- read_csv("total_s.csv")
```

About
==========================

Column {data-width = 400}
-------------------------

#### Background Information

In this Shiny app, we investigate many of the subtle variables of that affect the outcome of a soccer game. Using the UFEA Champions League statistics from the 2018-2023 seasons, we compare certain skills in different game situation throughout time.

Data source:  [FBREF Database](https://fbref.com/en/comps/8/history/Champions-League-Seasons)

[UFEA Champions League Official Website](https://www.uefa.com/uefachampionsleague/)

```{r, echo=FALSE}

renderImage({
    # Return a list
    list(src = "UEFA_Champions_League.svg.png",
         alt = "This is alternate text", width = 600, height = 600)
  })
```

Goals
=========================

Column
---------------------------

```{r, echo = FALSE}
titlePanel("Goal Metrics") 

inputPanel(
  selectInput("y", label = "Y-Axis Variable",
              choices = c(
                          "Expected Goals" = "xG",
                          "Non-Penalty Expected Goals" = "npxG",
                          "Average Shot Distance" = "Dist",
                          "Shots per 90 Minutes" = "Sh/90",
                          "Shot on Target %" = "SoT%", 
                          "Shot Creating Actions per 90 Minutes" = "SCA90",
                          "Proportion of Shot Creating Actions from Dead Balls" = "prop_SCA_dead")),
  selectInput("d", label = "Year",
  choices = c("All Years", unique(gs$Year))),
checkboxInput("rank_pos", "Show Final Placement", value = FALSE)
)

legend_order <- c("W", "F", "SF", "QF", "R16", "GR")

gs$Rank <- factor(gs$Rank, levels = legend_order)

  renderPlotly({
   if (input$rank_pos) 
    if (input$d == "All Years")
    gs |>
  plot_ly(x = ~Gls, y = ~.data[[input$y]], type = 'scatter', mode = 'markers', color = ~ Rank, text = ~paste("Team: ", Squad, '<br>Year: ', Year), height = 440) |>
      layout(xaxis = list(title = "Goals"),
             yaxis = list(title = if (input$y == "xG")
                                     "Expected Goals"
                                  else if (input$y == "npxG")
                                     "Non-Penalty Expected Goals"
                                  else if (input$y == "Dist")
                                     "Average Shot Distance"
                                  else if (input$y == "Sh/90")
                                     "Shots per 90 Minutes"
                                  else if (input$y == "SoT%")
                                     "Shot on Target %"
                                  else if (input$y == "SCA90")
                                     "Shot Creating Actions per 90 Minutes"
                                  else if (input$y == "prop_SCA_dead")
                                     "Proportion of Shot Creating Actions from Dead Balls"
                                  ))
    else 
       gs |>
    filter(Year %in% c(input$d)) |>
   plot_ly(x = ~Gls, y = ~.data[[input$y]], type = 'scatter', mode = 'markers', color = ~ Rank, text = ~paste("Team: ", Squad, '<br>Year: ', Year), height = 440) |>
      layout(xaxis = list(title = "Goals"),
             yaxis = list(title = if (input$y == "xG")
                                     "Expected Goals"
                                  else if (input$y == "npxG")
                                     "Non-Penalty Expected Goals"
                                  else if (input$y == "Dist")
                                     "Average Shot Distance"
                                  else if (input$y == "Sh/90")
                                     "Shots per 90 Minutes"
                                  else if (input$y == "SoT%")
                                     "Shot on Target %"
                                  else if (input$y == "SCA90")
                                     "Shot Creating Actions per 90 Minutes"
                                  else if (input$y == "prop_SCA_dead")
                                     "Proportion of Shot Creating Actions from Dead Balls"
                                  ))
  else if (!input$rank_pos)
    if (input$d == "All Years")
    gs |>
       plot_ly(x = ~Gls, y = ~.data[[input$y]], type = 'scatter', mode = 'markers', text = ~paste("Team: ", Squad, '<br>Year: ', Year), height = 440) |>
      layout(xaxis = list(title = "Goals"),
             yaxis = list(title = if (input$y == "xG")
                                     "Expected Goals"
                                  else if (input$y == "npxG")
                                     "Non-Penalty Expected Goals"
                                  else if (input$y == "Dist")
                                     "Average Shot Distance"
                                  else if (input$y == "Sh/90")
                                     "Shots per 90 Minutes"
                                  else if (input$y == "SoT%")
                                     "Shot on Target %"
                                  else if (input$y == "SCA90")
                                     "Shot Creating Actions per 90 Minutes"
                                  else if (input$y == "prop_SCA_dead")
                                     "Proportion of Shot Creating Actions from Dead Balls"
                                  ))
    else 
       gs |>
    filter(Year %in% c(input$d)) |>
       plot_ly(x = ~Gls, y = ~.data[[input$y]], type = 'scatter', mode = 'markers', text = ~paste("Team: ", Squad, '<br>Year: ', Year), height = 440) |>
      layout(xaxis = list(title = "Goals"),
             yaxis = list(title = if (input$y == "xG")
                                     "Expected Goals"
                                  else if (input$y == "npxG")
                                     "Non-Penalty Expected Goals"
                                  else if (input$y == "Dist")
                                     "Average Shot Distance"
                                  else if (input$y == "Sh/90")
                                     "Shots per 90 Minutes"
                                  else if (input$y == "SoT%")
                                     "Shot on Target %"
                                  else if (input$y == "SCA90")
                                     "Shot Creating Actions per 90 Minutes"
                                  else if (input$y == "prop_SCA_dead")
                                     "Proportion of Shot Creating Actions from Dead Balls"
                                  ))
})
```

```{r, echo = FALSE}
inputPanel(
  selectInput("year3", label = "Year",
    choices = c("All Years", unique(gs$Year))),
)

renderPlot({
  if (input$year3 == "All Years")
gs |>
ggplot() +
  geom_bar(aes(x = Rank, fill = performance)) +
  scale_x_discrete(limits = c("W", "F", "SF", "QF", "R16", "GR")) +
  labs(y = "Count", fill = "Goal Performance") +
    theme_minimal()
  else 
  gs |>
    filter(Year %in% c(input$year3)) |>
ggplot() +
  geom_bar(aes(x = Rank, fill = performance)) +
  scale_x_discrete(limits = c("W", "F", "SF", "QF", "R16", "GR")) +
  labs(y = "Count", fill = "Goal Performance") +
    theme_clean()
})
```

Column
---------------------------

```{r, echo = FALSE}
inputPanel(
  selectInput("y3", label = "Y-Axis Variable",
              choices = c(
                          "Expected Goals" = "xG",
                          "Goals" = "Gls",
                          "Non-Penalty Expected Goals" = "npxG",
                          "Average Shot Distance" = "Dist",
                          "Shots per 90 Minutes" = "Sh/90",
                          "Shot on Target %" = "SoT%", 
                          "Shot Creation Actions per 90 Minutes" = "SCA90",
                          "Proportion of Shot Creating Actions from Dead Balls" = "prop_SCA_dead",
                          "Goals per Shot on Target" = "G/SoT", 
                          "Goals Minus Expected Goals" = "G-xG"))
)

renderPlot({
  ggplot(gs, aes(x = Rank, y = .data[[input$y3]])) +
    geom_boxplot() +
    scale_x_discrete(limits = c("GR", "R16", "QF", "SF", "F", "W")) +
    labs(y = switch(input$y3,
                    "xG" = "Expected Goals",
                    "Gls" = "Goals",
                    "npxG" = "Non-Penalty Expected Goals",
                    "Dist" = "Average Shot Distance",
                    "Sh/90" = "Shots per 90 Minutes",
                    "SoT%" = "Shot on Target %",
                    "SCA90" = "Shot Creating Actions per 90 Minutes",
                    "prop_SCA_dead" = "Proportion of Shot Creating Actions from Dead Balls",
                    "G/SoT" = "Goals per Shot on Target", 
                    "G-xG" = "Goals Minus Expected Goals")) +
    theme_clean()
})
```

```{r, echo = FALSE}
inputPanel(
  selectInput("yr", "Year",
choices = c("All Years", unique(gs$Year))),
checkboxInput("penalty", "Include Penalty Shots", value = FALSE)
)

renderPlot({
  if(!input$penalty)
    if (input$yr == "All Years")
      gs |>
      ggplot(aes(x = `np:G-xG`)) +
      geom_density() +
      labs(x = "Non-Penalty Goals minus Non-Penalty Expected Goals", y = "Proportion of Teams", title = "Distribution of Goals Minus Expected Goals Values (Penalty and non-Penalty") +
    theme_clean()
    else
      gs |>
        filter(Year %in% c(input$yr)) |>
        ggplot(aes(x = `np:G-xG`)) +
        geom_density() +
        labs(x = "Non-Penalty Goals minus Non-Penalty Expected Goals", y = "Proportion of Teams", title = "Distribution of Goals Minus Expected Goals Values (Penalty and non-Penalty") +
    theme_clean()
  else
    if (input$yr == "All Years")
      gs |>
      ggplot(aes(x = `G-xG`)) +
      geom_density() +
        labs(x = "Goals minus Expected Goals", y = "Proportion of Teams", title = "Distribution of Goals Minus Expected Goals Values (Penalty and non-Penalty") +
    theme_clean()
    else
      gs |>
        filter(Year %in% c(input$yr)) |>
        ggplot(aes(x = `G-xG`)) +
        geom_density() +
        labs(x = "Goals minus Expected Goals", y = "Proportion of Teams", title = "Distribution of Goals Minus Expected Goals Values (Penalty and non-Penalty") +
    theme_clean()
})
```

Possession
=========================

Column
---------------------------

```{r, echo = FALSE}
titlePanel("Possession and Passing Metrics") 
inputPanel(
  selectInput("y2", label = "Y-Axis Variable",
              choices = c(
                          "Take-Ons Attempted" = "Att.x",
                          "Expected Assists" = "xA",
                          "Progressive Passes" = "PrgP",
                          "Touches in Defensive Third" = "Def 3rd", 
                          "Touches in Midfield Third" = "Mid 3rd",
                          "Touches in Attacking Third" = "Att 3rd",
                          "Proption of Touches in Defensive Third" = "prop_def_third",
                          "Proportion of Touches in Midfield Third" = "prop_mid_third",
                          "Proportion of Touches in Attacking Third" = "prop_att_third")),
  selectInput("d1", label = "Year",
  choices = c("All Years", unique(ps$Year))),
checkboxInput("rank_pos1", "Show Final Placement", value = FALSE)
)

ps$Rank <- factor(ps$Rank, levels = legend_order)

renderPlotly({
   if (input$rank_pos1) 
    if (input$d1 == "All Years")
    ps |>
  plot_ly(x = ~Poss, y = ~.data[[input$y2]], type = 'scatter', mode = 'markers', color = ~ Rank, text = ~paste("Team: ", Squad, '<br>Year: ', Year),
          height = 400) |>
      layout(xaxis = list(title = "Possession"),
             yaxis = list(title = if (input$y2 == "Att.x")
                                     "Take-Ons Attempted"
                                  else if (input$y2 == "xA")
                                     "Expected Assists"
                                  else if (input$y2 == "PrgP")
                                     "Progressive Passes"
                                  else if (input$y2 == "Def 3rd")
                                     "Touches in Defensive Third"
                                  else if (input$y2 == "Mid 3rd")
                                     "Touches in Midfield Third"
                                  else if (input$y2 == "Att 3rd")
                                     "Touches in Attacking Third"
                                  else if (input$y2 == "prop_def_third")
                                     "Proption of Touches in Defensive Third"
                                  else if (input$y2 == "prop_mid_third")
                                     "Proportion of Touches in Midfield Third"
                                  else if (input$y2 == "prop_att_third")
                                     "Proportion of Touches in Attacking Third"
                                  ))
    else 
       ps |>
    filter(Year %in% c(input$d1)) |>
   plot_ly(x = ~Poss, y = ~.data[[input$y2]], type = 'scatter', mode = 'markers', color = ~ Rank, text = ~paste("Team: ", Squad, '<br>Year: ', Year), height = 400) |>
      layout(xaxis = list(title = "Possession"),
             yaxis = list(title = if (input$y2 == "Att.x")
                                     "Take-Ons Attempted"
                                  else if (input$y2 == "xA")
                                     "Expected Assists"
                                  else if (input$y2 == "PrgP")
                                     "Progressive Passes"
                                  else if (input$y2 == "Def 3rd")
                                     "Touches in Defensive Third"
                                  else if (input$y2 == "Mid 3rd")
                                     "Touches in Midfield Third"
                                  else if (input$y2 == "Att 3rd")
                                     "Touches in Attacking Third"
                                  else if (input$y2 == "prop_def_third")
                                     "Proption of Touches in Defensive Third"
                                  else if (input$y2 == "prop_mid_third")
                                     "Proportion of Touches in Midfield Third"
                                  else if (input$y2 == "prop_att_third")
                                     "Proportion of Touches in Attacking Third"
                                  ))
  else if (!input$rank_pos1)
    if (input$d1 == "All Years")
    ps |>
       plot_ly(x = ~Poss, y = ~.data[[input$y2]], type = 'scatter', mode = 'markers', text = ~paste("Team: ", Squad, '<br>Year: ', Year), height = 400) |>
      layout(xaxis = list(title = "Possession"),
             yaxis = list(title = if (input$y2 == "Att.x")
                                     "Take-Ons Attempted"
                                  else if (input$y2 == "xA")
                                     "Expected Assists"
                                  else if (input$y2 == "PrgP")
                                     "Progressive Passes"
                                  else if (input$y2 == "Def 3rd")
                                     "Touches in Defensive Third"
                                  else if (input$y2 == "Mid 3rd")
                                     "Touches in Midfield Third"
                                  else if (input$y2 == "Att 3rd")
                                     "Touches in Attacking Third"
                                  else if (input$y2 == "prop_def_third")
                                     "Proption of Touches in Defensive Third"
                                  else if (input$y2 == "prop_mid_third")
                                     "Proportion of Touches in Midfield Third"
                                  else if (input$y2 == "prop_att_third")
                                     "Proportion of Touches in Attacking Third"
                                  ))
    else 
       ps |>
    filter(Year %in% c(input$d1)) |>
       plot_ly(x = ~Poss, y = ~.data[[input$y2]], type = 'scatter', mode = 'markers', text = ~paste("Team: ", Squad, '<br>Year: ', Year), height = 400) |>
      layout(xaxis = list(title = "Possession"),
             yaxis = list(title = if (input$y2 == "Att.x")
                                     "Take-Ons Attempted"
                                  else if (input$y2 == "xA")
                                     "Expected Assists"
                                  else if (input$y2 == "PrgP")
                                     "Progressive Passes"
                                  else if (input$y2 == "Def 3rd")
                                     "Touches in Defensive Third"
                                  else if (input$y2 == "Mid 3rd")
                                     "Touches in Midfield Third"
                                  else if (input$y2 == "Att 3rd")
                                     "Touches in Attacking Third"
                                  else if (input$y2 == "prop_def_third")
                                     "Proption of Touches in Defensive Third"
                                  else if (input$y2 == "prop_mid_third")
                                     "Proportion of Touches in Midfield Third"
                                  else if (input$y2 == "prop_att_third")
                                     "Proportion of Touches in Attacking Third"
                                  ))
})
```

```{r, echo = FALSE}
inputPanel(
  selectInput("third", label = "Third of Pitch",
              choices = c("Defensive Third" = "prop_def_third",
                          "Middle Third" = "prop_mid_third",
                          "Attacking Third" = "prop_att_third")), 
  selectInput("d2", "Year",
choices = c("All Years", unique(ps$Year))),
  sliderInput("pdt", label = "Proportion of Total Touches in Third",
              min = 0.1, max = 0.6, value = .32, step = .02)
)
renderPlot({
  if (input$d2 == "All Years")
  ps |>
    filter(.data[[input$third]] >= (input$pdt)) |>
    ggplot() +
    geom_point(aes(x = Poss, y = .data[[input$third]], color = Rank)) +
    labs(x = "Possession",
         y = switch(input$third,
                    "prop_def_third" = "Defensive Third",
                    "prop_mid_third" = "Middle Third",
                    "prop_att_third" = "Attacking Third"
)) +
    theme_clean()
  else 
  ps |>
    filter(Year %in% c(input$d2)) |>
    filter(.data[[input$third]] >= (input$pdt)) |>
    ggplot() +
    geom_point(aes(x = Poss, y = .data[[input$third]], color = Rank)) +
      labs(x = "Possession") +
    theme_clean()
}, height = 400)
```

Column
---------------------------

```{r, echo = FALSE}
inputPanel(
  selectInput("y1", label = "Y-Axis Variable",
              choices = c(
                           "Take-Ons Attempted per Match" = "takeons_attempted_90",
                          "Expected Assists" = "xA",
                          "Progressive Passes per Match" = "PrgP_90",
                          "Touches in Defensive Third per Match" = "def_third_touches_90", 
                          "Touches in Midfield Third per Match" = "mid_third_touches_90",
                          "Touches in Attacking Third per Match" = "att_third_touches_90",
                          "Progressive Carries per Match" = "PrgC_90",
                          "Pass Completion %" = "Cmp%",
                          "Crosses per Match" = "crosses_90",
                          "Key Passes per Match" = "kp_90"))
)

renderPlot({
  ggplot(ps, aes(x = Rank, y = .data[[input$y1]])) +
    geom_boxplot() +
    scale_x_discrete(limits = c("GR", "R16", "QF", "SF", "F", "W")) +
    labs(y = switch(input$y1,
                    "takeons_attempted_90" = "Take-Ons Attempted per Match",
                    "xA" = "Expected Assists",
                    "PrgP_90" = "Progressive Passes per Match",
                    "def_third_touches_90" = "Touches in Defensive Third per Match", 
                    "mid_third_touches_90" = "Touches in Midfield Third per Match",
                    "att_third_touches_90" = "Touches in Attacking Third per Match",
                    "PrgC_90" = "Progressive Carries per Match",
                    "Cmp%" = "Pass Completion %",
                    "crosses_90" = "Crosses per Match",
                    "kp_90" = "Key Passes per Match")) +
    theme_clean()
})
```

```{r, echo = FALSE}
inputPanel(
  selectInput("yr2", "Year",
choices = c("All Years", unique(gs$Year))),
)

renderPlot({
  if (input$yr2 == "All Years")
    ps |>
    ggplot(aes(x = `A-xAG`)) +
    geom_density() +
    labs(x = "Assists minus Expected Goals Assisted", y = "Proportion of Teams", title = "Distribution of Assists Minus Expected Assists Values") +
    theme_clean()
  else
    ps |>
      filter(Year %in% c(input$yr2)) |>
      ggplot(aes(x = `A-xAG`)) +
      geom_density() +
    labs(x = "Assists minus Expected Goals Assisted", y = "Proportion of Teams", title = "Distribution of Assists Minus Expected Assists Values") +
    theme_clean()
})
```

Defending and Goalkeeping
================================

Column
-------------

```{r, echo = FALSE}
titlePanel("Defensive Metrics")

inputPanel(
  selectInput("dsv", label = "Y-Axis Variable",
              choices = c(
                          "Save Percentage" = "Save%",
                          "Shots on Target Against" = "SoTA",
                          "Expected Goals Conceded" = "PSxG",
                          "Expected Goals Conceded minus Goals Allowed" = "PSxG+/-",
                          "Crosses Faced" = "Opp", 
                          "Tackles Won" = "TklW",
                          "Interceptions" = "Int",
                          "Blocks (Shots + Passes)" = "Blocks")),
  selectInput("d3", label = "Year",
  choices = c("All Years", unique(ds$Year))),
checkboxInput("rank_pos2", "Show Final Placement", value = FALSE)
)

ds$Rank <- factor(ds$Rank, levels = legend_order)

renderPlotly({
   if (input$rank_pos2) 
    if (input$d3 == "All Years")
    ds |>
  plot_ly(x = ~GA90, y = ~.data[[input$dsv]], type = 'scatter', mode = 'markers', color = ~ Rank, text = ~paste("Team: ", Squad, '<br>Year: ', Year), height = 400) |>
    layout(legend = list(c("W", "F", "SF", "QF", "R16", "GR")),
           xaxis = list(title = "Goals Against per 90 minutes"),
           yaxis = list(title = if (input$dsv == "Save%")
                                     "Save Percentage"
                                  else if (input$dsv == "SoTA")
                                     "Shots on Target Against"
                                  else if (input$dsv == "PSxG")
                                     "Expected Goals Conceded"
                                  else if (input$dsv == "PSxG+/-")
                                     "Expected Goals Conceded minus Goals Allowed"
                                  else if (input$dsv == "Opp")
                                     "Crosses Faced"
                                  else if (input$dsv == "TklW")
                                     "Tackles Won"
                                  else if (input$dsv == "Int")
                                     "Interceptions"
                                  else if (input$dsv == "Blocks")
                                     "Blocks (Shots + Passes)"
                                  ))
    else 
       ds |>
    filter(Year %in% c(input$d3)) |>
   plot_ly(x = ~GA90, y = ~.data[[input$dsv]], type = 'scatter', mode = 'markers', color = ~ Rank, text = ~paste("Team: ", Squad, '<br>Year: ', Year), height = 400) |>
  layout(legend = list(c("W", "F", "SF", "QF", "R16", "GR")),
           xaxis = list(title = "Goals Against per 90 minutes"),
         yaxis = list(title = if (input$dsv == "Save%")
                                     "Save Percentage"
                                  else if (input$dsv == "SoTA")
                                     "Shots on Target Against"
                                  else if (input$dsv == "PSxG")
                                     "Expected Goals Conceded"
                                  else if (input$dsv == "PSxG+/-")
                                     "Expected Goals Conceded minus Goals Allowed"
                                  else if (input$dsv == "Opp")
                                     "Crosses Faced"
                                  else if (input$dsv == "TklW")
                                     "Tackles Won"
                                  else if (input$dsv == "Int")
                                     "Interceptions"
                                  else if (input$dsv == "Blocks")
                                     "Blocks (Shots + Passes)"
                                  ))
  else if (!input$rank_pos2)
    if (input$d3 == "All Years")
    ds |>
       plot_ly(x = ~GA90, y = ~.data[[input$dsv]], type = 'scatter', mode = 'markers', text = ~paste("Team: ", Squad, '<br>Year: ', Year), height = 400) |>
  layout(legend = list(c("W", "F", "SF", "QF", "R16", "GR")),
           xaxis = list(title = "Goals Against per 90 minutes"),
           yaxis = list(title = if (input$dsv == "Save%")
                                     "Save Percentage"
                                  else if (input$dsv == "SoTA")
                                     "Shots on Target Against"
                                  else if (input$dsv == "PSxG")
                                     "Expected Goals Conceded"
                                  else if (input$dsv == "PSxG+/-")
                                     "Expected Goals Conceded minus Goals Allowed"
                                  else if (input$dsv == "Opp")
                                     "Crosses Faced"
                                  else if (input$dsv == "TklW")
                                     "Tackles Won"
                                  else if (input$dsv == "Int")
                                     "Interceptions"
                                  else if (input$dsv == "Blocks")
                                     "Blocks (Shots + Passes)"
                                  ))
    else 
       ds |>
    filter(Year %in% c(input$d3)) |>
       plot_ly(x = ~GA90, y = ~.data[[input$dsv]], type = 'scatter', mode = 'markers', text = ~paste("Team: ", Squad, '<br>Year: ', Year), height = 400) |>
       layout(legend = list(c("W", "F", "SF", "QF", "R16", "GR")),
           xaxis = list(title = "Goals Against per 90 minutes"),
           yaxis = list(title = if (input$dsv == "Save%")
                                     "Save Percentage"
                                  else if (input$dsv == "SoTA")
                                     "Shots on Target Against"
                                  else if (input$dsv == "PSxG")
                                     "Expected Goals Conceded"
                                  else if (input$dsv == "PSxG+/-")
                                     "Expected Goals Conceded minus Goals Allowed"
                                  else if (input$dsv == "Opp")
                                     "Crosses Faced"
                                  else if (input$dsv == "TklW")
                                     "Tackles Won"
                                  else if (input$dsv == "Int")
                                     "Interceptions"
                                  else if (input$dsv == "Blocks")
                                     "Blocks (Shots + Passes)"
                                  ))
})
```

```{r, echo = FALSE}
inputPanel(
  selectInput("x_var", label = "X-Axis Variable",
              choices = c(
                          "Proportion Tackles Won" = "prop_tkl_w",
                          "Percent of Dribblers Tackled" = "Tkl%",
                          "Challenges Lost" = "Lost",
                          "Shots Blocked" = "Sh",
                          "Interceptions" = "Int", 
                          "Errors" = "Err"))
)

renderPlot({
  ggplot(ds, aes(.data[[input$x_var]], Squad)) +
    geom_line(aes(group = Squad)) +
    geom_point(aes(color = save_performance)) +
    labs(color = "Save Performance", x = switch(input$x_var,
                    "prop_tkl_w" = "Proportion Tackles Won",
                    "Tkl%" = "Percent of Dribblers Tackled",
                    "Lost" = "Challenges Lost",
                    "Sh" = "Shots Blocked",
                    "Int" = "Interceptions",
                    "Err" = "Errors")) +
    theme_clean()
},
height = 1000)
```

Column
----------

```{r, echo = FALSE}
inputPanel(
  selectInput("dsv1", label = "Y-Axis Variable",
              choices = c(
                          "Goals Allowed per 90 Minutes" = "GA90",
                          "Save Percentage" = "Save%",
                          "Post-Shot Expected Goals" = "PSxG",
                          "Post-Shot Expected Goals - Goals Allowed" = "PSxG+/-",
                          "Crossed Attempted Against per Match" = "opp_90", 
                          "Tackles per Match" = "tkl_90",
                          "Interceptions per Match" = "int_90",
                          "Tackles + Interceptions per Match" = "tkl_int_90",
                          "Tackles in Defensive Third per Match" = "def_3rd_90",
                      "Tackles in Attacking Third per Match" = "att_3rd_90"))
)

renderPlot({
  ggplot(ds, aes(x = Rank, y = .data[[input$dsv1]])) +
    geom_boxplot() +
    scale_x_discrete(limits = c("GR", "R16", "QF", "SF", "F", "W")) +
    labs(y = switch(input$dsv1,
                    "GA90" = "Goals Allowed per 90 Minutes",
                    "Save%" = "Save Percentage",
                    "PSxG" = "Post-Shot Expected Goals",
                    "PSxG+/-" = "Post-Shot Expected Goals - Goals Allowed",
                    "opp_90" = "Crossed Attempted Against per Match", 
                    "tkl_90" = "Tackles per Match",
                    "int_90" = "Interceptions per Match",
                    "tkl_int_90" = "Tackles + Interceptions per Match",
                    "def_3rd_90" = "Tackles in Defensive Third per Match",
                    "att_3rd_90" = "Tackles in Attacking Third per Match")) +
    theme_clean()
})
```

```{r, echo = FALSE}
inputPanel(
  selectInput("yr3", "Year",
choices = c("All Years", unique(gs$Year))),
checkboxInput("ninety", "Per 90 Minutes", value = FALSE)
)

renderPlot({
  if(!input$ninety)
    if (input$yr3 == "All Years")
      ds |>
      ggplot(aes(x = `PSxG+/-`)) +
      geom_density() +
      labs(x = "Post-Shot Expected Goals minus Goals Allowed", y = "Proportion of Teams", title = "Distribution of Post-Shot Expected Goals Minus Goals Allowed (Total or per 90 Minutes)") +
    theme_clean()
    else
      ds |>
        filter(Year %in% c(input$yr3)) |>
        ggplot(aes(x = `PSxG+/-`)) +
        geom_density() +
      labs(x = "Post-Shot Expected Goals minus Goals Allowed", y = "Proportion of Teams", title = "Distribution of Post-Shot Expected Goals Minus Goals Allowed (Total or per 90 Minutes)") +
    theme_clean()
  else
    if (input$yr3 == "All Years")
      ds |>
      ggplot(aes(x = `/90`)) +
      geom_density() +
      labs(x = "Post-Shot Expected Goals minus Goals Allowed per 90 Minutes", y = "Proportion of Teams", title = "Distribution of Post-Shot Expected Goals Minus Goals Allowed (Total or per 90 Minutes)") +
    theme_clean()
    else
      ds |>
        filter(Year %in% c(input$yr3)) |>
        ggplot(aes(x = `/90`)) +
        geom_density() +
      labs(x = "Post-Shot Expected Goals minus Goals Allowed per 90 Minutes", y = "Proportion of Teams", title = "Distribution of Post-Shot Expected Goals Minus Goals Allowed (Total or per 90 Minutes)") +
    theme_clean()
})
```


Conclusion
================================

Column
-------------

```{r, echo = FALSE}
inputPanel(
  selectInput("yr4", "Year",
choices = c("22/23" = "22/23", "21/22" = "21/22", "20/21" = "20/21", "19/20" = "19/20", "18/19" = "18/19")))

renderPlotly({
total_s |>
  select(Squad, Year, xG, SCA90, `SoT/90`, Dist, xAG, kp_90, takeons_attempted_90, PrgC_90, SoTA, PSxG, tkl_int_90, opp_90) |>
  filter(Year %in% c(input$yr4)) |>
  select(!Year) |>
 melt(id.vars = "Squad") |>
plot_ly(
  y = ~Squad, 
  x = ~variable,
  z = ~value,
  type = "heatmap",
  height = 750) |>
  layout(xaxis = list(title = "Variable"), fill = list(title = "Value"),
         zaxis = list(title = "Value"))
})
```

------------
------------
```{r}
renderTable({
  total_s |>
    select(Squad, Rank, Year) |>
    filter(Year %in% c(input$yr4)) |>
    gt()
})
```
